name: Elixir CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install openssl&libssl-dev
      run: |
        sudo apt-get update
        sudo apt-get install -y openssl libssl1.1
    - name: Display openssl&libssl-dev versions
      run: dpkg -l openssl libssl-dev | grep '^ii' | cut -c5-
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.6.5 # Define the elixir version [required]
        otp-version: 21.3 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
    - name: Check mix format
      run: mix format --check-formatted
